# Generated by Django 3.0.2 on 2020-02-03 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_pass', models.CharField(max_length=30)),
                ('current_room', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('player_avatar', models.IntegerField(default=0)),
            ],
        ),
    ]
